SUPABASE_URL="https://myohjatijsjbalthdwkc.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15b2hqYXRpc2piYWx0aGRid2t1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4Mzg4ODAsImV4cCI6MjA3NjQxNDg4MH0.G_U_gLazeQpNHQSTQpYmQvr5sPyLYwjLeBk8SCxjIrk"
